### PR TITLE
Added Swedish language

### PR DESCRIPTION
**Pull request by jyourstone**
Added Swedish language

### CODE REVIEW

**Comment by bobbingwide** [comment]
Hi Johan, thanks for that. I notice you've done the translations on  wordpress.org. I'm not sure how to get them approved. There is an issue with the translation of the example value 6.95
The code doesn't support localised values for currency.

**Comment by jyourstone** [comment]
Hello,

Yes I translated it at wordpress.org as well but it needs to be approved by someone from the Swedish language team it seems. A developer for another plugin has added a request for me to be added as an "approver". I'm not sure if I will be able to approve the language for your plugin as well then but we'll see.

Regarding the example value 6.95, I'm not quite sure what you mean. I'm using your plugin on a test site and it seems to be working fine there.

**Comment by bobbingwide** [comment]
Re: 6,95. If you use commas rather than decimal points then the values will be parsed incorrectly. The code treats commas as separators. 

100 | 6.95 | will work
100 | 6,95 | won't work as expected
101.99 | 7.01 | will work
101,99 | 7.02 | won't work as expected.

It's just the , in 6,95 that needs changing.... until I've dealt with #11

**Comment by jyourstone** [comment]
Ah my mistake, I thought I used a dot, not a comma. I changed it on Polyglots and also asked someone to approve my translations there, so you can disregard this pull request since using Polyglots is much better.

**Comment by bobbingwide** [comment]
Polyglots is fine for plugins on WordPress.org but I have other plugin as well. Would you also care to translate the multi rate version?

**Comment by jyourstone** [comment]
I corrected the string to use a dot instead of comma. I also sent you an e-mail regarding the translation of the multi rate version.

**Pull request merged**
